# Generated by Django 6.0.3 on 2026-03-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_config',
            field=models.JSONField(blank=True, default=dict, help_text='Avatar configuration options for DiceBear avatar generation'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], db_index=True, help_text='User gender for avatar generation', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='URL to profile picture (deprecated, use avatar_config instead)'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gender'], name='users_gender_c12881_idx'),
        ),
    ]
