# Generated by Django 6.0.3 on 2026-05-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verification_sent_at_and_more'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='subscribers', through='packages.Subscription', to='packages.package'),
        ),
    ]
