# Generated by Django 6.0.3 on 2026-05-08 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Basic, Pro, Enterprise', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current price e.g. 9.99', max_digits=8)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Pre-discount price shown as strikethrough.', max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 code e.g. USD, GHS', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], db_index=True, default='monthly', max_length=10)),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Free trial days. 0 means no trial.')),
                ('is_unlimited', models.BooleanField(default=False, help_text='Grants access to all active courses.')),
                ('max_courses', models.PositiveIntegerField(blank=True, help_text='Max courses student can enrol in. Null means unlimited.', null=True)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='For institution plans. Null means single student.', null=True)),
                ('ai_credits_per_month', models.PositiveIntegerField(default=0, help_text='AI generation requests per month. 0 means no AI access.')),
                ('ai_question_generation', models.BooleanField(default=False, help_text='Can generate custom practice questions using AI.')),
                ('ai_explanations', models.BooleanField(default=False, help_text='Gets AI-powered explanations for incorrect answers.')),
                ('includes_certificate', models.BooleanField(default=False, help_text='Awards certificate on course completion.')),
                ('can_download_materials', models.BooleanField(default=False, help_text='Can download materials for offline use.')),
                ('is_featured', models.BooleanField(default=True, help_text='Highlights package on pricing page.')),
                ('badge_text', models.CharField(blank=True, default='', help_text="e.g. 'Most Popular'.", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order on pricing page.')),
                ('includes_video_lessons', models.BooleanField(default=False, help_text='Whether this package includes video lessons.')),
                ('video_quality', models.CharField(blank=True, choices=[('sd', 'Standard Definition (480p)'), ('hd', 'High Definition (720p)'), ('fhd', 'Full HD (1080p)')], default='sd', help_text='Maximum video quality available under this package.', max_length=5)),
                ('text_to_audio', models.BooleanField(default=False, help_text='Students can listen to module content read aloud.')),
                ('audio_to_text', models.BooleanField(default=False, help_text='Students can ask questions using their voice.')),
                ('audio_minutes_per_month', models.PositiveIntegerField(default=0, help_text='Monthly audio processing minutes. 0 means no audio access.')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Subjects accessible under this package. Empty means all.', related_name='packages', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='trial', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null means lifetime / never expires.', null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='When the trial period ends.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True, help_text='Whether subscription renews automatically.')),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Payment gateway transaction reference.', max_length=200)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('too_expensive', 'Too Expensive'), ('not_useful', 'Not Useful'), ('found_better', 'Found a Better Alternative'), ('technical', 'Technical Issues'), ('other', 'Other')], default='', max_length=20)),
                ('cancellation_note', models.TextField(blank=True, default='', help_text='Optional note from student on cancellation.')),
                ('ai_credits_used', models.PositiveIntegerField(default=0)),
                ('audio_minutes_used', models.PositiveIntegerField(default=0)),
                ('usage_cycle_started_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['trial', 'active', 'paused'])), fields=('user',), name='unique_active_subscription_per_user')],
            },
        ),
    ]
