# Generated by Django 6.0.3 on 2026-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner Only'), ('intermediate', 'Up to Intermediate'), ('advanced', 'All Levels')], db_index=True, default='advanced', help_text='Maximum course difficulty level accessible under this package.', max_length=12),
        ),
    ]
