# Generated by Django 6.0.3 on 2026-05-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_max_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='max_difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner Only'), ('intermediate', 'Up to Intermediate'), ('advanced', 'Up to Advanced'), ('expert', 'All Levels')], db_index=True, default='advanced', help_text='Maximum course difficulty level accessible under this package.', max_length=12),
        ),
    ]
