# Generated by Django 6.0.3 on 2026-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_max_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='current_period_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the current billing cycle ends.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_period_ends_at',
            field=models.DateTimeField(blank=True, help_text='Grace period ends 3 days after billing cycle ends.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace Period'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='trial', max_length=12),
        ),
    ]
