# Generated by Django 6.0.3 on 2026-05-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_subscription_current_period_ends_at_and_more'),
        ('subjects', '0004_course_prerequisites_course_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='max_courses',
        ),
        migrations.AddField(
            model_name='package',
            name='max_courses_at_level',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum courses allowed AT the ceiling difficulty level. Courses below the ceiling are always unlimited. Null means unlimited at ceiling too.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='ai_credits_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='ai_explanations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='ai_question_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='audio_minutes_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='audio_to_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='can_download_materials',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='package',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='includes_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='includes_video_lessons',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_unlimited',
            field=models.BooleanField(default=False, help_text='Grants unlimited access to ALL courses at ALL levels.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner Only'), ('intermediate', 'Up to Intermediate'), ('advanced', 'All Levels')], db_index=True, default='beginner', help_text='The highest difficulty level this package can access.', max_length=12),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='package',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='packages', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='package',
            name='text_to_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='trial_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='video_quality',
            field=models.CharField(blank=True, choices=[('sd', 'Standard Definition (480p)'), ('hd', 'High Definition (720p)'), ('fhd', 'Full HD (1080p)')], default='sd', max_length=5),
        ),
    ]
