# Generated by Django 6.0.3 on 2026-05-09 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_max_difficulty'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed')], db_index=True, default='active', max_length=10)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Completion percentage 0-100')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registrations', to='subjects.course')),
                ('subscription', models.ForeignKey(help_text='The subscription that granted access to this course.', on_delete=django.db.models.deletion.RESTRICT, related_name='registrations', to='packages.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course registration',
                'verbose_name_plural': 'course registrations',
                'ordering': ['-enrolled_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_registration')],
            },
        ),
    ]
