# Generated by Django 6.0.3 on 2026-05-10 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_courseregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='progress',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time purchase price. Null means not available for purchase.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time purchase price. Null means not available for purchase.', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='progress', to='subjects.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course progress',
                'verbose_name_plural': 'course progress',
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_progress')],
            },
        ),
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], db_index=True, default='active', max_length=12)),
                ('deactivated_by_student', models.BooleanField(default=False)),
                ('deactivated_by_admin', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchases', to='subjects.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course purchase',
                'verbose_name_plural': 'course purchases',
                'ordering': ['-purchased_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_purchase')],
            },
        ),
    ]
